# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TariffForProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TarifsForCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('mark', models.PositiveSmallIntegerField(choices=[(1, '='), (2, '>'), (3, '->')], default=1)),
                ('weight', models.IntegerField(default=0)),
                ('delivery_time_from', models.IntegerField(default=1)),
                ('delivery_time_to', models.IntegerField(default=1)),
                ('price', models.FloatField(default=1)),
                ('type', models.SmallIntegerField(choices=[(1, 'Standart'), (2, 'Express')], default=1)),
            ],
        ),
    ]
