# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20170926_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariffforproduct',
            options={'verbose_name': 'Tariff for product', 'verbose_name_plural': 'Tariffs for products'},
        ),
        migrations.AlterModelOptions(
            name='tarifsforcountry',
            options={'verbose_name': 'Tariff for country', 'verbose_name_plural': 'Tariffs for countries'},
        ),
    ]
