# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20171024_1011'),
        ('delivery', '0005_auto_20171024_1011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tariffforproduct',
            unique_together=set([('tariff', 'product')]),
        ),
    ]
