# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_auto_20170925_0607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressfarm',
            options={'verbose_name': 'Farm address', 'verbose_name_plural': 'Farm addresses'},
        ),
        migrations.AlterModelOptions(
            name='farm',
            options={'verbose_name': 'Farm', 'verbose_name_plural': 'Farms'},
        ),
    ]
