# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='notexistcity',
            options={'verbose_name': 'Nonexistent city', 'verbose_name_plural': 'Nonexistent cities'},
        ),
        migrations.AlterModelOptions(
            name='notexistregion',
            options={'verbose_name': 'Nonexistent region', 'verbose_name_plural': 'Nonexistent regions'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
    ]
