# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
        ('catalog', '0003_auto_20170919_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.ProfileBusiness')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bestproduct',
            unique_together=set([('product', 'seller')]),
        ),
    ]
