# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170926_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.Product'),
        ),
    ]
