# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20171009_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
        ),
    ]
