# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_auto_20171005_0800'),
        ('catalog', '0007_auto_20171009_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupForProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Profile')),
            ],
        ),
    ]
