# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_auto_20171005_0800'),
        ('catalog', '0008_groupforprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryForProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoryForProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Profile')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.SubCategory')),
            ],
        ),
    ]
