# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 05:00
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_categoryforprofile_subcategoryforprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10, null=True),
        ),
    ]
