# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 12:58
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20171013_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgproduct',
            name='img',
            field=models.ImageField(upload_to=catalog.models.pi_directory_path),
        ),
    ]
