# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20171024_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classproduct',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
