# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmountProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('delivery_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.PositiveSmallIntegerField(choices=[(1, 'Standart'), (2, 'Express')], default=1)),
                ('order_status', models.SmallIntegerField(choices=[(1, 'Cart'), (2, 'Order')], default=1)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(1, 'PayPal')], default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'paid for'), (3, 'ready to ship'), (4, 'shipped'), (5, 'canceled'), (6, 'delivered')], default=1)),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('customer_notificated', models.BooleanField(default=0)),
                ('tracking_number', models.CharField(blank=True, max_length=25, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
