# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20170921_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'paid for'), (3, 'ready to ship'), (4, 'canceled'), (5, 'shipped'), (6, 'delivered'), (7, 'failed')]),
        ),
    ]
