# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20170921_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountproduct',
            options={'verbose_name': 'String in order', 'verbose_name_plural': 'Strings in order'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Order status', 'verbose_name_plural': 'Order statuses'},
        ),
    ]
